

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/weather
    driver-class-name: org.mariadb.jdbc.Driver
    username: choidongkuen
    password: ehdrms6390

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


#logging:
#  pattern:
#    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
#  level:
#    org:
#      springframework: DEBUG

